name: 'dbt_project'
version: '1.0.0'

# Nome do Profile do profile.yml do ~/.dbt.profiles.yml
profile: 'dbt_project'

# Definição do nome das principais pastar do projeto
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:          # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Exemplos de Variáveis

vars:
  ambiente: 'desenvolvimento'
  data_minima: '2023-01-01'
  schema_nome: 'desenvolvimento_schema'


models:                 # Configurações para cada modelo
  dbt_project:
    
    staging:
      schema: staging
      materialized: table
      tags: ['staging']
    
    intermediate:
      materialized: ephemeral
      tags: ['intermediate']

    marts:
      schema: marts
      materialized: table
      tags: ['marts']

seeds:
  dbt_project:
    schema: seeds
    materialized: seed
    tags: ['seeds']
  
snapshots:
  dbt_project:
    tags: ['snapshots']
    schema: snapshots