dbt_project_real:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_DEV_PROJECT') }}"
      dataset: "{{ env_var('DBT_DEV_SCHEMA') }}"
      keyfile: "{{ env_var('GCP_DEV_KEYFILE_PATH') }}"
      threads: 4
  
